CREATE TABLE Sales
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales1
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales2
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales3
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales4
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales5
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales6
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales7
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales8
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales11
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales12
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales13
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales14
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales15
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales16
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales17
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales18
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales21
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales22
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales23
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales24
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales25
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales26
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales27
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales28
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales31
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales32
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales33
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales34
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales35
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales36
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales37
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales38
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales41
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales42
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales43
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales44
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales45
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales46
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales47
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales48
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales51
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales52
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales53
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales54
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales55
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales56
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales57
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales58
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales61
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales62
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales63
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales64
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales65
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales66
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales67
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales68
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales71
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales72
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales73
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales74
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales75
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales76
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales77
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales78
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales81
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales82
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales83
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales84
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales85
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales86
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales87
      (	Order_ID INT PRIMARY KEY     NOT NULL);
CREATE TABLE Sales88
      (	Order_ID INT PRIMARY KEY     NOT NULL);
commit;